version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  name_template: "{{.Tag}}"
  draft: false
  prerelease: auto
