// Code generated by MockGen. DO NOT EDIT.
// Source: teams/ops_interface.go
//
// Generated by this command:
//
//	mockgen --source=teams/ops_interface.go --destination=internal/testutil/mock_team_ops.go --package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/pzsp-teams/lib/models"
	gomock "go.uber.org/mock/gomock"
)

// MockteamsOps is a mock of teamsOps interface.
type MockteamsOps struct {
	ctrl     *gomock.Controller
	recorder *MockteamsOpsMockRecorder
	isgomock struct{}
}

// MockteamsOpsMockRecorder is the mock recorder for MockteamsOps.
type MockteamsOpsMockRecorder struct {
	mock *MockteamsOps
}

// NewMockteamsOps creates a new mock instance.
func NewMockteamsOps(ctrl *gomock.Controller) *MockteamsOps {
	mock := &MockteamsOps{ctrl: ctrl}
	mock.recorder = &MockteamsOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamsOps) EXPECT() *MockteamsOpsMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockteamsOps) AddMember(ctx context.Context, teamID, userRef string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, userRef, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockteamsOpsMockRecorder) AddMember(ctx, teamID, userRef, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockteamsOps)(nil).AddMember), ctx, teamID, userRef, isOwner)
}

// Archive mocks base method.
func (m *MockteamsOps) Archive(ctx context.Context, teamID, teamRef string, spoReadOnlyForMembers *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, teamID, teamRef, spoReadOnlyForMembers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockteamsOpsMockRecorder) Archive(ctx, teamID, teamRef, spoReadOnlyForMembers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockteamsOps)(nil).Archive), ctx, teamID, teamRef, spoReadOnlyForMembers)
}

// CreateFromTemplate mocks base method.
func (m *MockteamsOps) CreateFromTemplate(ctx context.Context, displayName, description string, ownerIDs, membersIDs []string, visibility string, includeMe bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, displayName, description, ownerIDs, membersIDs, visibility, includeMe)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockteamsOpsMockRecorder) CreateFromTemplate(ctx, displayName, description, ownerIDs, membersIDs, visibility, includeMe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockteamsOps)(nil).CreateFromTemplate), ctx, displayName, description, ownerIDs, membersIDs, visibility, includeMe)
}

// CreateViaGroup mocks base method.
func (m *MockteamsOps) CreateViaGroup(ctx context.Context, displayName, mailNickname, visibility string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateViaGroup", ctx, displayName, mailNickname, visibility)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateViaGroup indicates an expected call of CreateViaGroup.
func (mr *MockteamsOpsMockRecorder) CreateViaGroup(ctx, displayName, mailNickname, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateViaGroup", reflect.TypeOf((*MockteamsOps)(nil).CreateViaGroup), ctx, displayName, mailNickname, visibility)
}

// DeleteTeam mocks base method.
func (m *MockteamsOps) DeleteTeam(ctx context.Context, teamID, teamRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, teamID, teamRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *MockteamsOpsMockRecorder) DeleteTeam(ctx, teamID, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*MockteamsOps)(nil).DeleteTeam), ctx, teamID, teamRef)
}

// GetMemberByID mocks base method.
func (m *MockteamsOps) GetMemberByID(ctx context.Context, teamID, memberID string) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberByID", ctx, teamID, memberID)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberByID indicates an expected call of GetMemberByID.
func (mr *MockteamsOpsMockRecorder) GetMemberByID(ctx, teamID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberByID", reflect.TypeOf((*MockteamsOps)(nil).GetMemberByID), ctx, teamID, memberID)
}

// GetTeamByID mocks base method.
func (m *MockteamsOps) GetTeamByID(ctx context.Context, teamID string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByID", ctx, teamID)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByID indicates an expected call of GetTeamByID.
func (mr *MockteamsOpsMockRecorder) GetTeamByID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByID", reflect.TypeOf((*MockteamsOps)(nil).GetTeamByID), ctx, teamID)
}

// ListMembers mocks base method.
func (m *MockteamsOps) ListMembers(ctx context.Context, teamID string) ([]*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID)
	ret0, _ := ret[0].([]*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockteamsOpsMockRecorder) ListMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockteamsOps)(nil).ListMembers), ctx, teamID)
}

// ListMyJoinedTeams mocks base method.
func (m *MockteamsOps) ListMyJoinedTeams(ctx context.Context) ([]*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyJoinedTeams", ctx)
	ret0, _ := ret[0].([]*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyJoinedTeams indicates an expected call of ListMyJoinedTeams.
func (mr *MockteamsOpsMockRecorder) ListMyJoinedTeams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyJoinedTeams", reflect.TypeOf((*MockteamsOps)(nil).ListMyJoinedTeams), ctx)
}

// RemoveMember mocks base method.
func (m *MockteamsOps) RemoveMember(ctx context.Context, teamID, memberID, userRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, memberID, userRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockteamsOpsMockRecorder) RemoveMember(ctx, teamID, memberID, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockteamsOps)(nil).RemoveMember), ctx, teamID, memberID, userRef)
}

// RestoreDeletedTeam mocks base method.
func (m *MockteamsOps) RestoreDeletedTeam(ctx context.Context, deletedGroupID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeletedTeam", ctx, deletedGroupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDeletedTeam indicates an expected call of RestoreDeletedTeam.
func (mr *MockteamsOpsMockRecorder) RestoreDeletedTeam(ctx, deletedGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeletedTeam", reflect.TypeOf((*MockteamsOps)(nil).RestoreDeletedTeam), ctx, deletedGroupID)
}

// Unarchive mocks base method.
func (m *MockteamsOps) Unarchive(ctx context.Context, teamID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockteamsOpsMockRecorder) Unarchive(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockteamsOps)(nil).Unarchive), ctx, teamID)
}

// UpdateMemberRoles mocks base method.
func (m *MockteamsOps) UpdateMemberRoles(ctx context.Context, teamID, memberID string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamID, memberID, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockteamsOpsMockRecorder) UpdateMemberRoles(ctx, teamID, memberID, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockteamsOps)(nil).UpdateMemberRoles), ctx, teamID, memberID, isOwner)
}

// UpdateTeam mocks base method.
func (m *MockteamsOps) UpdateTeam(ctx context.Context, teamID string, update *models.TeamUpdate, teamRef string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, teamID, update, teamRef)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockteamsOpsMockRecorder) UpdateTeam(ctx, teamID, update, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockteamsOps)(nil).UpdateTeam), ctx, teamID, update, teamRef)
}
