// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/user.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
)

// MockUserAPI is a mock of UserAPI interface.
type MockUserAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUserAPIMockRecorder
}

// MockUserAPIMockRecorder is the mock recorder for MockUserAPI.
type MockUserAPIMockRecorder struct {
	mock *MockUserAPI
}

// NewMockUserAPI creates a new mock instance.
func NewMockUserAPI(ctrl *gomock.Controller) *MockUserAPI {
	mock := &MockUserAPI{ctrl: ctrl}
	mock.recorder = &MockUserAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAPI) EXPECT() *MockUserAPIMockRecorder {
	return m.recorder
}

// GetUserByEmailOrUPN mocks base method.
func (m *MockUserAPI) GetUserByEmailOrUPN(ctx context.Context, emailOrUPN string) (models.Userable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailOrUPN", ctx, emailOrUPN)
	ret0, _ := ret[0].(models.Userable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetUserByEmailOrUPN indicates an expected call of GetUserByEmailOrUPN.
func (mr *MockUserAPIMockRecorder) GetUserByEmailOrUPN(ctx, emailOrUPN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailOrUPN", reflect.TypeOf((*MockUserAPI)(nil).GetUserByEmailOrUPN), ctx, emailOrUPN)
}
