// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/team.go
//
// Generated by this command:
//
//	mockgen --source=internal/api/team.go --destination=internal/testutil/mock_team_api.go --package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamAPI is a mock of TeamAPI interface.
type MockTeamAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTeamAPIMockRecorder
	isgomock struct{}
}

// MockTeamAPIMockRecorder is the mock recorder for MockTeamAPI.
type MockTeamAPIMockRecorder struct {
	mock *MockTeamAPI
}

// NewMockTeamAPI creates a new mock instance.
func NewMockTeamAPI(ctrl *gomock.Controller) *MockTeamAPI {
	mock := &MockTeamAPI{ctrl: ctrl}
	mock.recorder = &MockTeamAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamAPI) EXPECT() *MockTeamAPIMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamAPI) AddMember(ctx context.Context, teamID, userRef string, roles []string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, userRef, roles)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamAPIMockRecorder) AddMember(ctx, teamID, userRef, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamAPI)(nil).AddMember), ctx, teamID, userRef, roles)
}

// Archive mocks base method.
func (m *MockTeamAPI) Archive(ctx context.Context, teamID string, spoReadOnlyForMembers *bool) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, teamID, spoReadOnlyForMembers)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockTeamAPIMockRecorder) Archive(ctx, teamID, spoReadOnlyForMembers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockTeamAPI)(nil).Archive), ctx, teamID, spoReadOnlyForMembers)
}

// CreateFromTemplate mocks base method.
func (m *MockTeamAPI) CreateFromTemplate(ctx context.Context, displayName, description string, owners []string) (string, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, displayName, description, owners)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockTeamAPIMockRecorder) CreateFromTemplate(ctx, displayName, description, owners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockTeamAPI)(nil).CreateFromTemplate), ctx, displayName, description, owners)
}

// CreateViaGroup mocks base method.
func (m *MockTeamAPI) CreateViaGroup(ctx context.Context, displayName, mailNickname, visibility string) (string, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateViaGroup", ctx, displayName, mailNickname, visibility)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateViaGroup indicates an expected call of CreateViaGroup.
func (mr *MockTeamAPIMockRecorder) CreateViaGroup(ctx, displayName, mailNickname, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateViaGroup", reflect.TypeOf((*MockTeamAPI)(nil).CreateViaGroup), ctx, displayName, mailNickname, visibility)
}

// Delete mocks base method.
func (m *MockTeamAPI) Delete(ctx context.Context, teamID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamAPIMockRecorder) Delete(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamAPI)(nil).Delete), ctx, teamID)
}

// Get mocks base method.
func (m *MockTeamAPI) Get(ctx context.Context, teamID string) (models.Teamable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamID)
	ret0, _ := ret[0].(models.Teamable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamAPIMockRecorder) Get(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamAPI)(nil).Get), ctx, teamID)
}

// GetMember mocks base method.
func (m *MockTeamAPI) GetMember(ctx context.Context, teamID, memberID string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, teamID, memberID)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockTeamAPIMockRecorder) GetMember(ctx, teamID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockTeamAPI)(nil).GetMember), ctx, teamID, memberID)
}

// ListAllMessages mocks base method.
func (m *MockTeamAPI) ListAllMessages(ctx context.Context, teamID string, startTime, endTime *time.Time, top *int32) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMessages", ctx, teamID, startTime, endTime, top)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListAllMessages indicates an expected call of ListAllMessages.
func (mr *MockTeamAPIMockRecorder) ListAllMessages(ctx, teamID, startTime, endTime, top any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMessages", reflect.TypeOf((*MockTeamAPI)(nil).ListAllMessages), ctx, teamID, startTime, endTime, top)
}

// ListMembers mocks base method.
func (m *MockTeamAPI) ListMembers(ctx context.Context, teamID string) (models.ConversationMemberCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID)
	ret0, _ := ret[0].(models.ConversationMemberCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockTeamAPIMockRecorder) ListMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockTeamAPI)(nil).ListMembers), ctx, teamID)
}

// ListMyJoined mocks base method.
func (m *MockTeamAPI) ListMyJoined(ctx context.Context) (models.TeamCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyJoined", ctx)
	ret0, _ := ret[0].(models.TeamCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMyJoined indicates an expected call of ListMyJoined.
func (mr *MockTeamAPIMockRecorder) ListMyJoined(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyJoined", reflect.TypeOf((*MockTeamAPI)(nil).ListMyJoined), ctx)
}

// RemoveMember mocks base method.
func (m *MockTeamAPI) RemoveMember(ctx context.Context, teamID, memberID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, memberID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamAPIMockRecorder) RemoveMember(ctx, teamID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamAPI)(nil).RemoveMember), ctx, teamID, memberID)
}

// RestoreDeleted mocks base method.
func (m *MockTeamAPI) RestoreDeleted(ctx context.Context, deletedGroupID string) (models.DirectoryObjectable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeleted", ctx, deletedGroupID)
	ret0, _ := ret[0].(models.DirectoryObjectable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// RestoreDeleted indicates an expected call of RestoreDeleted.
func (mr *MockTeamAPIMockRecorder) RestoreDeleted(ctx, deletedGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeleted", reflect.TypeOf((*MockTeamAPI)(nil).RestoreDeleted), ctx, deletedGroupID)
}

// Unarchive mocks base method.
func (m *MockTeamAPI) Unarchive(ctx context.Context, teamID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, teamID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockTeamAPIMockRecorder) Unarchive(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockTeamAPI)(nil).Unarchive), ctx, teamID)
}

// Update mocks base method.
func (m *MockTeamAPI) Update(ctx context.Context, teamID string, patch *models.Team) (models.Teamable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, teamID, patch)
	ret0, _ := ret[0].(models.Teamable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamAPIMockRecorder) Update(ctx, teamID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamAPI)(nil).Update), ctx, teamID, patch)
}

// UpdateMemberRoles mocks base method.
func (m *MockTeamAPI) UpdateMemberRoles(ctx context.Context, teamID, memberID string, roles []string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamID, memberID, roles)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockTeamAPIMockRecorder) UpdateMemberRoles(ctx, teamID, memberID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockTeamAPI)(nil).UpdateMemberRoles), ctx, teamID, memberID, roles)
}
