// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/user.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
)

// MockUsersAPI is a mock of UsersAPI interface.
type MockUsersAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUsersAPIMockRecorder
}

// MockUsersAPIMockRecorder is the mock recorder for MockUsersAPI.
type MockUsersAPIMockRecorder struct {
	mock *MockUsersAPI
}

// NewMockUsersAPI creates a new mock instance.
func NewMockUsersAPI(ctrl *gomock.Controller) *MockUsersAPI {
	mock := &MockUsersAPI{ctrl: ctrl}
	mock.recorder = &MockUsersAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersAPI) EXPECT() *MockUsersAPIMockRecorder {
	return m.recorder
}

// GetUserByEmailOrUPN mocks base method.
func (m *MockUsersAPI) GetUserByEmailOrUPN(ctx context.Context, emailOrUPN string) (models.Userable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailOrUPN", ctx, emailOrUPN)
	ret0, _ := ret[0].(models.Userable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetUserByEmailOrUPN indicates an expected call of GetUserByEmailOrUPN.
func (mr *MockUsersAPIMockRecorder) GetUserByEmailOrUPN(ctx, emailOrUPN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailOrUPN", reflect.TypeOf((*MockUsersAPI)(nil).GetUserByEmailOrUPN), ctx, emailOrUPN)
}
