// Code generated by MockGen. DO NOT EDIT.
// Source: internal/resolver/channel_cacheable.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockChannelResolver is a mock of ChannelResolver interface.
type MockChannelResolver struct {
	ctrl     *gomock.Controller
	recorder *MockChannelResolverMockRecorder
}

// MockChannelResolverMockRecorder is the mock recorder for MockChannelResolver.
type MockChannelResolverMockRecorder struct {
	mock *MockChannelResolver
}

// NewMockChannelResolver creates a new mock instance.
func NewMockChannelResolver(ctrl *gomock.Controller) *MockChannelResolver {
	mock := &MockChannelResolver{ctrl: ctrl}
	mock.recorder = &MockChannelResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelResolver) EXPECT() *MockChannelResolverMockRecorder {
	return m.recorder
}

// ResolveChannelMemberRefToID mocks base method.
func (m *MockChannelResolver) ResolveChannelMemberRefToID(ctx context.Context, teamID, channelID, userRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveChannelMemberRefToID", ctx, teamID, channelID, userRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveChannelMemberRefToID indicates an expected call of ResolveChannelMemberRefToID.
func (mr *MockChannelResolverMockRecorder) ResolveChannelMemberRefToID(ctx, teamID, channelID, userRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveChannelMemberRefToID", reflect.TypeOf((*MockChannelResolver)(nil).ResolveChannelMemberRefToID), ctx, teamID, channelID, userRef)
}

// ResolveChannelRefToID mocks base method.
func (m *MockChannelResolver) ResolveChannelRefToID(ctx context.Context, teamID, channelRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveChannelRefToID", ctx, teamID, channelRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveChannelRefToID indicates an expected call of ResolveChannelRefToID.
func (mr *MockChannelResolverMockRecorder) ResolveChannelRefToID(ctx, teamID, channelRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveChannelRefToID", reflect.TypeOf((*MockChannelResolver)(nil).ResolveChannelRefToID), ctx, teamID, channelRef)
}
