// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/channel.go
//
// Generated by this command:
//
//	mockgen --source=internal/api/channel.go --destination=internal/testutil/mock_channel_api.go --package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelAPI is a mock of ChannelAPI interface.
type MockChannelAPI struct {
	ctrl     *gomock.Controller
	recorder *MockChannelAPIMockRecorder
	isgomock struct{}
}

// MockChannelAPIMockRecorder is the mock recorder for MockChannelAPI.
type MockChannelAPIMockRecorder struct {
	mock *MockChannelAPI
}

// NewMockChannelAPI creates a new mock instance.
func NewMockChannelAPI(ctrl *gomock.Controller) *MockChannelAPI {
	mock := &MockChannelAPI{ctrl: ctrl}
	mock.recorder = &MockChannelAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelAPI) EXPECT() *MockChannelAPIMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockChannelAPI) AddMember(ctx context.Context, teamID, channelID, userRef string, roles []string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, channelID, userRef, roles)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockChannelAPIMockRecorder) AddMember(ctx, teamID, channelID, userRef, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockChannelAPI)(nil).AddMember), ctx, teamID, channelID, userRef, roles)
}

// CreatePrivateChannelWithMembers mocks base method.
func (m *MockChannelAPI) CreatePrivateChannelWithMembers(ctx context.Context, teamID, displayName string, memberIDs, ownersID []string) (models.Channelable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChannelWithMembers", ctx, teamID, displayName, memberIDs, ownersID)
	ret0, _ := ret[0].(models.Channelable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreatePrivateChannelWithMembers indicates an expected call of CreatePrivateChannelWithMembers.
func (mr *MockChannelAPIMockRecorder) CreatePrivateChannelWithMembers(ctx, teamID, displayName, memberIDs, ownersID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChannelWithMembers", reflect.TypeOf((*MockChannelAPI)(nil).CreatePrivateChannelWithMembers), ctx, teamID, displayName, memberIDs, ownersID)
}

// CreateStandardChannel mocks base method.
func (m *MockChannelAPI) CreateStandardChannel(ctx context.Context, teamID string, channel models.Channelable) (models.Channelable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStandardChannel", ctx, teamID, channel)
	ret0, _ := ret[0].(models.Channelable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateStandardChannel indicates an expected call of CreateStandardChannel.
func (mr *MockChannelAPIMockRecorder) CreateStandardChannel(ctx, teamID, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStandardChannel", reflect.TypeOf((*MockChannelAPI)(nil).CreateStandardChannel), ctx, teamID, channel)
}

// DeleteChannel mocks base method.
func (m *MockChannelAPI) DeleteChannel(ctx context.Context, teamID, channelID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, teamID, channelID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelAPIMockRecorder) DeleteChannel(ctx, teamID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannelAPI)(nil).DeleteChannel), ctx, teamID, channelID)
}

// GetChannel mocks base method.
func (m *MockChannelAPI) GetChannel(ctx context.Context, teamID, channelID string) (models.Channelable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, teamID, channelID)
	ret0, _ := ret[0].(models.Channelable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockChannelAPIMockRecorder) GetChannel(ctx, teamID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockChannelAPI)(nil).GetChannel), ctx, teamID, channelID)
}

// GetMessage mocks base method.
func (m *MockChannelAPI) GetMessage(ctx context.Context, teamID, channelID, messageID string) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, teamID, channelID, messageID)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockChannelAPIMockRecorder) GetMessage(ctx, teamID, channelID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockChannelAPI)(nil).GetMessage), ctx, teamID, channelID, messageID)
}

// GetReply mocks base method.
func (m *MockChannelAPI) GetReply(ctx context.Context, teamID, channelID, messageID, replyID string) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReply", ctx, teamID, channelID, messageID, replyID)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetReply indicates an expected call of GetReply.
func (mr *MockChannelAPIMockRecorder) GetReply(ctx, teamID, channelID, messageID, replyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReply", reflect.TypeOf((*MockChannelAPI)(nil).GetReply), ctx, teamID, channelID, messageID, replyID)
}

// ListChannels mocks base method.
func (m *MockChannelAPI) ListChannels(ctx context.Context, teamID string) (models.ChannelCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx, teamID)
	ret0, _ := ret[0].(models.ChannelCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockChannelAPIMockRecorder) ListChannels(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockChannelAPI)(nil).ListChannels), ctx, teamID)
}

// ListMembers mocks base method.
func (m *MockChannelAPI) ListMembers(ctx context.Context, teamID, channelID string) (models.ConversationMemberCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID, channelID)
	ret0, _ := ret[0].(models.ConversationMemberCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockChannelAPIMockRecorder) ListMembers(ctx, teamID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockChannelAPI)(nil).ListMembers), ctx, teamID, channelID)
}

// ListMessages mocks base method.
func (m *MockChannelAPI) ListMessages(ctx context.Context, teamID, channelID string, top *int32, includeSystem bool) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, teamID, channelID, top, includeSystem)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChannelAPIMockRecorder) ListMessages(ctx, teamID, channelID, top, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChannelAPI)(nil).ListMessages), ctx, teamID, channelID, top, includeSystem)
}

// ListMessagesNext mocks base method.
func (m *MockChannelAPI) ListMessagesNext(ctx context.Context, teamID, channelID, nextLink string, includeSystem bool) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagesNext", ctx, teamID, channelID, nextLink, includeSystem)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMessagesNext indicates an expected call of ListMessagesNext.
func (mr *MockChannelAPIMockRecorder) ListMessagesNext(ctx, teamID, channelID, nextLink, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagesNext", reflect.TypeOf((*MockChannelAPI)(nil).ListMessagesNext), ctx, teamID, channelID, nextLink, includeSystem)
}

// ListReplies mocks base method.
func (m *MockChannelAPI) ListReplies(ctx context.Context, teamID, channelID, messageID string, top *int32, includeSystem bool) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, teamID, channelID, messageID, top, includeSystem)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockChannelAPIMockRecorder) ListReplies(ctx, teamID, channelID, messageID, top, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockChannelAPI)(nil).ListReplies), ctx, teamID, channelID, messageID, top, includeSystem)
}

// ListRepliesNext mocks base method.
func (m *MockChannelAPI) ListRepliesNext(ctx context.Context, teamID, channelID, messageID, nextLink string, includeSystem bool) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepliesNext", ctx, teamID, channelID, messageID, nextLink, includeSystem)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListRepliesNext indicates an expected call of ListRepliesNext.
func (mr *MockChannelAPIMockRecorder) ListRepliesNext(ctx, teamID, channelID, messageID, nextLink, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepliesNext", reflect.TypeOf((*MockChannelAPI)(nil).ListRepliesNext), ctx, teamID, channelID, messageID, nextLink, includeSystem)
}

// RemoveMember mocks base method.
func (m *MockChannelAPI) RemoveMember(ctx context.Context, teamID, channelID, memberID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, channelID, memberID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockChannelAPIMockRecorder) RemoveMember(ctx, teamID, channelID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockChannelAPI)(nil).RemoveMember), ctx, teamID, channelID, memberID)
}

// SendMessage mocks base method.
func (m *MockChannelAPI) SendMessage(ctx context.Context, teamID, channelID, content, contentType string, mentions []models.ChatMessageMentionable) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, teamID, channelID, content, contentType, mentions)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChannelAPIMockRecorder) SendMessage(ctx, teamID, channelID, content, contentType, mentions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChannelAPI)(nil).SendMessage), ctx, teamID, channelID, content, contentType, mentions)
}

// SendReply mocks base method.
func (m *MockChannelAPI) SendReply(ctx context.Context, teamID, channelID, messageID, content, contentType string, mentions []models.ChatMessageMentionable) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReply", ctx, teamID, channelID, messageID, content, contentType, mentions)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SendReply indicates an expected call of SendReply.
func (mr *MockChannelAPIMockRecorder) SendReply(ctx, teamID, channelID, messageID, content, contentType, mentions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReply", reflect.TypeOf((*MockChannelAPI)(nil).SendReply), ctx, teamID, channelID, messageID, content, contentType, mentions)
}

// UpdateMemberRoles mocks base method.
func (m *MockChannelAPI) UpdateMemberRoles(ctx context.Context, teamID, channelID, memberID string, roles []string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamID, channelID, memberID, roles)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockChannelAPIMockRecorder) UpdateMemberRoles(ctx, teamID, channelID, memberID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockChannelAPI)(nil).UpdateMemberRoles), ctx, teamID, channelID, memberID, roles)
}
