// Code generated by MockGen. DO NOT EDIT.
// Source: channels/ops_interface.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sender "github.com/pzsp-teams/lib/internal/sender"
	models "github.com/pzsp-teams/lib/models"
)

// MockchannelOps is a mock of channelOps interface.
type MockchannelOps struct {
	ctrl     *gomock.Controller
	recorder *MockchannelOpsMockRecorder
}

// MockchannelOpsMockRecorder is the mock recorder for MockchannelOps.
type MockchannelOpsMockRecorder struct {
	mock *MockchannelOps
}

// NewMockchannelOps creates a new mock instance.
func NewMockchannelOps(ctrl *gomock.Controller) *MockchannelOps {
	mock := &MockchannelOps{ctrl: ctrl}
	mock.recorder = &MockchannelOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchannelOps) EXPECT() *MockchannelOpsMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockchannelOps) AddMember(ctx context.Context, teamID, channelID, userID string, isOwner bool) (*models.Member, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, channelID, userID, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockchannelOpsMockRecorder) AddMember(ctx, teamID, channelID, userID, isOwner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockchannelOps)(nil).AddMember), ctx, teamID, channelID, userID, isOwner)
}

// CreatePrivateChannel mocks base method.
func (m *MockchannelOps) CreatePrivateChannel(ctx context.Context, teamID, name string, memberIDs, ownerIDs []string) (*models.Channel, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChannel", ctx, teamID, name, memberIDs, ownerIDs)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreatePrivateChannel indicates an expected call of CreatePrivateChannel.
func (mr *MockchannelOpsMockRecorder) CreatePrivateChannel(ctx, teamID, name, memberIDs, ownerIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChannel", reflect.TypeOf((*MockchannelOps)(nil).CreatePrivateChannel), ctx, teamID, name, memberIDs, ownerIDs)
}

// CreateStandardChannel mocks base method.
func (m *MockchannelOps) CreateStandardChannel(ctx context.Context, teamID, name string) (*models.Channel, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStandardChannel", ctx, teamID, name)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateStandardChannel indicates an expected call of CreateStandardChannel.
func (mr *MockchannelOpsMockRecorder) CreateStandardChannel(ctx, teamID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStandardChannel", reflect.TypeOf((*MockchannelOps)(nil).CreateStandardChannel), ctx, teamID, name)
}

// DeleteChannel mocks base method.
func (m *MockchannelOps) DeleteChannel(ctx context.Context, teamID, channelID, channelRef string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, teamID, channelID, channelRef)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockchannelOpsMockRecorder) DeleteChannel(ctx, teamID, channelID, channelRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockchannelOps)(nil).DeleteChannel), ctx, teamID, channelID, channelRef)
}

// GetChannelByID mocks base method.
func (m *MockchannelOps) GetChannelByID(ctx context.Context, teamID, channelID string) (*models.Channel, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelByID", ctx, teamID, channelID)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetChannelByID indicates an expected call of GetChannelByID.
func (mr *MockchannelOpsMockRecorder) GetChannelByID(ctx, teamID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelByID", reflect.TypeOf((*MockchannelOps)(nil).GetChannelByID), ctx, teamID, channelID)
}

// GetMessage mocks base method.
func (m *MockchannelOps) GetMessage(ctx context.Context, teamID, channelID, messageID string) (*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, teamID, channelID, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockchannelOpsMockRecorder) GetMessage(ctx, teamID, channelID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockchannelOps)(nil).GetMessage), ctx, teamID, channelID, messageID)
}

// GetReply mocks base method.
func (m *MockchannelOps) GetReply(ctx context.Context, teamID, channelID, messageID, replyID string) (*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReply", ctx, teamID, channelID, messageID, replyID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetReply indicates an expected call of GetReply.
func (mr *MockchannelOpsMockRecorder) GetReply(ctx, teamID, channelID, messageID, replyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReply", reflect.TypeOf((*MockchannelOps)(nil).GetReply), ctx, teamID, channelID, messageID, replyID)
}

// ListChannelsByTeamID mocks base method.
func (m *MockchannelOps) ListChannelsByTeamID(ctx context.Context, teamID string) ([]*models.Channel, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannelsByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]*models.Channel)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListChannelsByTeamID indicates an expected call of ListChannelsByTeamID.
func (mr *MockchannelOpsMockRecorder) ListChannelsByTeamID(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannelsByTeamID", reflect.TypeOf((*MockchannelOps)(nil).ListChannelsByTeamID), ctx, teamID)
}

// ListMembers mocks base method.
func (m *MockchannelOps) ListMembers(ctx context.Context, teamID, channelID string) ([]*models.Member, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID, channelID)
	ret0, _ := ret[0].([]*models.Member)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockchannelOpsMockRecorder) ListMembers(ctx, teamID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockchannelOps)(nil).ListMembers), ctx, teamID, channelID)
}

// ListMessages mocks base method.
func (m *MockchannelOps) ListMessages(ctx context.Context, teamID, channelID string, opts *models.ListMessagesOptions) ([]*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, teamID, channelID, opts)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockchannelOpsMockRecorder) ListMessages(ctx, teamID, channelID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockchannelOps)(nil).ListMessages), ctx, teamID, channelID, opts)
}

// ListReplies mocks base method.
func (m *MockchannelOps) ListReplies(ctx context.Context, teamID, channelID, messageID string, opts *models.ListMessagesOptions) ([]*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, teamID, channelID, messageID, opts)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockchannelOpsMockRecorder) ListReplies(ctx, teamID, channelID, messageID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockchannelOps)(nil).ListReplies), ctx, teamID, channelID, messageID, opts)
}

// RemoveMember mocks base method.
func (m *MockchannelOps) RemoveMember(ctx context.Context, teamID, channelID, memberID, userRef string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, channelID, memberID, userRef)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockchannelOpsMockRecorder) RemoveMember(ctx, teamID, channelID, memberID, userRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockchannelOps)(nil).RemoveMember), ctx, teamID, channelID, memberID, userRef)
}

// SendMessage mocks base method.
func (m *MockchannelOps) SendMessage(ctx context.Context, teamID, channelID string, body models.MessageBody) (*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, teamID, channelID, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockchannelOpsMockRecorder) SendMessage(ctx, teamID, channelID, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockchannelOps)(nil).SendMessage), ctx, teamID, channelID, body)
}

// SendReply mocks base method.
func (m *MockchannelOps) SendReply(ctx context.Context, teamID, channelID, messageID string, body models.MessageBody) (*models.Message, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReply", ctx, teamID, channelID, messageID, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SendReply indicates an expected call of SendReply.
func (mr *MockchannelOpsMockRecorder) SendReply(ctx, teamID, channelID, messageID, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReply", reflect.TypeOf((*MockchannelOps)(nil).SendReply), ctx, teamID, channelID, messageID, body)
}

// UpdateMemberRoles mocks base method.
func (m *MockchannelOps) UpdateMemberRoles(ctx context.Context, teamID, channelID, memberID string, isOwner bool) (*models.Member, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamID, channelID, memberID, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockchannelOpsMockRecorder) UpdateMemberRoles(ctx, teamID, channelID, memberID, isOwner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockchannelOps)(nil).UpdateMemberRoles), ctx, teamID, channelID, memberID, isOwner)
}

// Wait mocks base method.
func (m *MockchannelOps) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait.
func (mr *MockchannelOpsMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockchannelOps)(nil).Wait))
}
