// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/chat.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
)

// MockOneOnOneChatAPI is a mock of OneOnOneChatAPI interface.
type MockOneOnOneChatAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOneOnOneChatAPIMockRecorder
}

// MockOneOnOneChatAPIMockRecorder is the mock recorder for MockOneOnOneChatAPI.
type MockOneOnOneChatAPIMockRecorder struct {
	mock *MockOneOnOneChatAPI
}

// NewMockOneOnOneChatAPI creates a new mock instance.
func NewMockOneOnOneChatAPI(ctrl *gomock.Controller) *MockOneOnOneChatAPI {
	mock := &MockOneOnOneChatAPI{ctrl: ctrl}
	mock.recorder = &MockOneOnOneChatAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOneOnOneChatAPI) EXPECT() *MockOneOnOneChatAPIMockRecorder {
	return m.recorder
}

// CreateOneOnOneChat mocks base method.
func (m *MockOneOnOneChatAPI) CreateOneOnOneChat(ctx context.Context, recipientRef string) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneOnOneChat", ctx, recipientRef)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateOneOnOneChat indicates an expected call of CreateOneOnOneChat.
func (mr *MockOneOnOneChatAPIMockRecorder) CreateOneOnOneChat(ctx, recipientRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneOnOneChat", reflect.TypeOf((*MockOneOnOneChatAPI)(nil).CreateOneOnOneChat), ctx, recipientRef)
}

// MockGroupChatAPI is a mock of GroupChatAPI interface.
type MockGroupChatAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGroupChatAPIMockRecorder
}

// MockGroupChatAPIMockRecorder is the mock recorder for MockGroupChatAPI.
type MockGroupChatAPIMockRecorder struct {
	mock *MockGroupChatAPI
}

// NewMockGroupChatAPI creates a new mock instance.
func NewMockGroupChatAPI(ctrl *gomock.Controller) *MockGroupChatAPI {
	mock := &MockGroupChatAPI{ctrl: ctrl}
	mock.recorder = &MockGroupChatAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupChatAPI) EXPECT() *MockGroupChatAPIMockRecorder {
	return m.recorder
}

// AddMemberToGroupChat mocks base method.
func (m *MockGroupChatAPI) AddMemberToGroupChat(ctx context.Context, chatID, userRef string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberToGroupChat", ctx, chatID, userRef)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// AddMemberToGroupChat indicates an expected call of AddMemberToGroupChat.
func (mr *MockGroupChatAPIMockRecorder) AddMemberToGroupChat(ctx, chatID, userRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberToGroupChat", reflect.TypeOf((*MockGroupChatAPI)(nil).AddMemberToGroupChat), ctx, chatID, userRef)
}

// CreateGroupChat mocks base method.
func (m *MockGroupChatAPI) CreateGroupChat(ctx context.Context, recipientRefs []string, topic string, includeMe bool) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupChat", ctx, recipientRefs, topic, includeMe)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateGroupChat indicates an expected call of CreateGroupChat.
func (mr *MockGroupChatAPIMockRecorder) CreateGroupChat(ctx, recipientRefs, topic, includeMe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupChat", reflect.TypeOf((*MockGroupChatAPI)(nil).CreateGroupChat), ctx, recipientRefs, topic, includeMe)
}

// ListGroupChatMembers mocks base method.
func (m *MockGroupChatAPI) ListGroupChatMembers(ctx context.Context, chatID string) (models.ConversationMemberCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupChatMembers", ctx, chatID)
	ret0, _ := ret[0].(models.ConversationMemberCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListGroupChatMembers indicates an expected call of ListGroupChatMembers.
func (mr *MockGroupChatAPIMockRecorder) ListGroupChatMembers(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupChatMembers", reflect.TypeOf((*MockGroupChatAPI)(nil).ListGroupChatMembers), ctx, chatID)
}

// RemoveMemberFromGroupChat mocks base method.
func (m *MockGroupChatAPI) RemoveMemberFromGroupChat(ctx context.Context, chatID, memberID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMemberFromGroupChat", ctx, chatID, memberID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// RemoveMemberFromGroupChat indicates an expected call of RemoveMemberFromGroupChat.
func (mr *MockGroupChatAPIMockRecorder) RemoveMemberFromGroupChat(ctx, chatID, memberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMemberFromGroupChat", reflect.TypeOf((*MockGroupChatAPI)(nil).RemoveMemberFromGroupChat), ctx, chatID, memberID)
}

// UpdateGroupChatTopic mocks base method.
func (m *MockGroupChatAPI) UpdateGroupChatTopic(ctx context.Context, chatID, topic string) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupChatTopic", ctx, chatID, topic)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// UpdateGroupChatTopic indicates an expected call of UpdateGroupChatTopic.
func (mr *MockGroupChatAPIMockRecorder) UpdateGroupChatTopic(ctx, chatID, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupChatTopic", reflect.TypeOf((*MockGroupChatAPI)(nil).UpdateGroupChatTopic), ctx, chatID, topic)
}

// MockChatAPI is a mock of ChatAPI interface.
type MockChatAPI struct {
	ctrl     *gomock.Controller
	recorder *MockChatAPIMockRecorder
}

// MockChatAPIMockRecorder is the mock recorder for MockChatAPI.
type MockChatAPIMockRecorder struct {
	mock *MockChatAPI
}

// NewMockChatAPI creates a new mock instance.
func NewMockChatAPI(ctrl *gomock.Controller) *MockChatAPI {
	mock := &MockChatAPI{ctrl: ctrl}
	mock.recorder = &MockChatAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatAPI) EXPECT() *MockChatAPIMockRecorder {
	return m.recorder
}

// AddMemberToGroupChat mocks base method.
func (m *MockChatAPI) AddMemberToGroupChat(ctx context.Context, chatID, userRef string) (models.ConversationMemberable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberToGroupChat", ctx, chatID, userRef)
	ret0, _ := ret[0].(models.ConversationMemberable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// AddMemberToGroupChat indicates an expected call of AddMemberToGroupChat.
func (mr *MockChatAPIMockRecorder) AddMemberToGroupChat(ctx, chatID, userRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberToGroupChat", reflect.TypeOf((*MockChatAPI)(nil).AddMemberToGroupChat), ctx, chatID, userRef)
}

// CreateGroupChat mocks base method.
func (m *MockChatAPI) CreateGroupChat(ctx context.Context, recipientRefs []string, topic string, includeMe bool) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupChat", ctx, recipientRefs, topic, includeMe)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateGroupChat indicates an expected call of CreateGroupChat.
func (mr *MockChatAPIMockRecorder) CreateGroupChat(ctx, recipientRefs, topic, includeMe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupChat", reflect.TypeOf((*MockChatAPI)(nil).CreateGroupChat), ctx, recipientRefs, topic, includeMe)
}

// CreateOneOnOneChat mocks base method.
func (m *MockChatAPI) CreateOneOnOneChat(ctx context.Context, recipientRef string) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneOnOneChat", ctx, recipientRef)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateOneOnOneChat indicates an expected call of CreateOneOnOneChat.
func (mr *MockChatAPIMockRecorder) CreateOneOnOneChat(ctx, recipientRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneOnOneChat", reflect.TypeOf((*MockChatAPI)(nil).CreateOneOnOneChat), ctx, recipientRef)
}

// DeleteMessage mocks base method.
func (m *MockChatAPI) DeleteMessage(ctx context.Context, chatID, messageID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, chatID, messageID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockChatAPIMockRecorder) DeleteMessage(ctx, chatID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockChatAPI)(nil).DeleteMessage), ctx, chatID, messageID)
}

// GetMessage mocks base method.
func (m *MockChatAPI) GetMessage(ctx context.Context, chatID, messageID string) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, chatID, messageID)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockChatAPIMockRecorder) GetMessage(ctx, chatID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockChatAPI)(nil).GetMessage), ctx, chatID, messageID)
}

// ListAllMessages mocks base method.
func (m *MockChatAPI) ListAllMessages(ctx context.Context, startTime, endTime *time.Time, top *int32) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMessages", ctx, startTime, endTime, top)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListAllMessages indicates an expected call of ListAllMessages.
func (mr *MockChatAPIMockRecorder) ListAllMessages(ctx, startTime, endTime, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMessages", reflect.TypeOf((*MockChatAPI)(nil).ListAllMessages), ctx, startTime, endTime, top)
}

// ListChats mocks base method.
func (m *MockChatAPI) ListChats(ctx context.Context, chatType *string) (models.ChatCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChats", ctx, chatType)
	ret0, _ := ret[0].(models.ChatCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListChats indicates an expected call of ListChats.
func (mr *MockChatAPIMockRecorder) ListChats(ctx, chatType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChats", reflect.TypeOf((*MockChatAPI)(nil).ListChats), ctx, chatType)
}

// ListGroupChatMembers mocks base method.
func (m *MockChatAPI) ListGroupChatMembers(ctx context.Context, chatID string) (models.ConversationMemberCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupChatMembers", ctx, chatID)
	ret0, _ := ret[0].(models.ConversationMemberCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListGroupChatMembers indicates an expected call of ListGroupChatMembers.
func (mr *MockChatAPIMockRecorder) ListGroupChatMembers(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupChatMembers", reflect.TypeOf((*MockChatAPI)(nil).ListGroupChatMembers), ctx, chatID)
}

// ListMessages mocks base method.
func (m *MockChatAPI) ListMessages(ctx context.Context, chatID string) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, chatID)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChatAPIMockRecorder) ListMessages(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChatAPI)(nil).ListMessages), ctx, chatID)
}

// ListPinnedMessages mocks base method.
func (m *MockChatAPI) ListPinnedMessages(ctx context.Context, chatID string) (models.ChatMessageCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPinnedMessages", ctx, chatID)
	ret0, _ := ret[0].(models.ChatMessageCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListPinnedMessages indicates an expected call of ListPinnedMessages.
func (mr *MockChatAPIMockRecorder) ListPinnedMessages(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPinnedMessages", reflect.TypeOf((*MockChatAPI)(nil).ListPinnedMessages), ctx, chatID)
}

// PinMessage mocks base method.
func (m *MockChatAPI) PinMessage(ctx context.Context, chatID, messageID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMessage", ctx, chatID, messageID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// PinMessage indicates an expected call of PinMessage.
func (mr *MockChatAPIMockRecorder) PinMessage(ctx, chatID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMessage", reflect.TypeOf((*MockChatAPI)(nil).PinMessage), ctx, chatID, messageID)
}

// RemoveMemberFromGroupChat mocks base method.
func (m *MockChatAPI) RemoveMemberFromGroupChat(ctx context.Context, chatID, memberID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMemberFromGroupChat", ctx, chatID, memberID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// RemoveMemberFromGroupChat indicates an expected call of RemoveMemberFromGroupChat.
func (mr *MockChatAPIMockRecorder) RemoveMemberFromGroupChat(ctx, chatID, memberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMemberFromGroupChat", reflect.TypeOf((*MockChatAPI)(nil).RemoveMemberFromGroupChat), ctx, chatID, memberID)
}

// SendMessage mocks base method.
func (m *MockChatAPI) SendMessage(ctx context.Context, chatID, content, contentType string, mentions []models.ChatMessageMentionable) (models.ChatMessageable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, content, contentType, mentions)
	ret0, _ := ret[0].(models.ChatMessageable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatAPIMockRecorder) SendMessage(ctx, chatID, content, contentType, mentions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatAPI)(nil).SendMessage), ctx, chatID, content, contentType, mentions)
}

// UnpinMessage mocks base method.
func (m *MockChatAPI) UnpinMessage(ctx context.Context, chatID, pinnedID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinMessage", ctx, chatID, pinnedID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// UnpinMessage indicates an expected call of UnpinMessage.
func (mr *MockChatAPIMockRecorder) UnpinMessage(ctx, chatID, pinnedID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinMessage", reflect.TypeOf((*MockChatAPI)(nil).UnpinMessage), ctx, chatID, pinnedID)
}

// UpdateGroupChatTopic mocks base method.
func (m *MockChatAPI) UpdateGroupChatTopic(ctx context.Context, chatID, topic string) (models.Chatable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupChatTopic", ctx, chatID, topic)
	ret0, _ := ret[0].(models.Chatable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// UpdateGroupChatTopic indicates an expected call of UpdateGroupChatTopic.
func (mr *MockChatAPIMockRecorder) UpdateGroupChatTopic(ctx, chatID, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupChatTopic", reflect.TypeOf((*MockChatAPI)(nil).UpdateGroupChatTopic), ctx, chatID, topic)
}
