// Code generated by MockGen. DO NOT EDIT.
// Source: internal/resolver/team_cacheable.go
//
// Generated by this command:
//
//	mockgen --source=internal/resolver/team_cacheable.go --destination=internal/testutil/mock_team_resolver.go --package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTeamResolver is a mock of TeamResolver interface.
type MockTeamResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTeamResolverMockRecorder
	isgomock struct{}
}

// MockTeamResolverMockRecorder is the mock recorder for MockTeamResolver.
type MockTeamResolverMockRecorder struct {
	mock *MockTeamResolver
}

// NewMockTeamResolver creates a new mock instance.
func NewMockTeamResolver(ctrl *gomock.Controller) *MockTeamResolver {
	mock := &MockTeamResolver{ctrl: ctrl}
	mock.recorder = &MockTeamResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamResolver) EXPECT() *MockTeamResolverMockRecorder {
	return m.recorder
}

// ResolveTeamMemberRefToID mocks base method.
func (m *MockTeamResolver) ResolveTeamMemberRefToID(ctx context.Context, teamID, userRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTeamMemberRefToID", ctx, teamID, userRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTeamMemberRefToID indicates an expected call of ResolveTeamMemberRefToID.
func (mr *MockTeamResolverMockRecorder) ResolveTeamMemberRefToID(ctx, teamID, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTeamMemberRefToID", reflect.TypeOf((*MockTeamResolver)(nil).ResolveTeamMemberRefToID), ctx, teamID, userRef)
}

// ResolveTeamRefToID mocks base method.
func (m *MockTeamResolver) ResolveTeamRefToID(ctx context.Context, teamRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTeamRefToID", ctx, teamRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTeamRefToID indicates an expected call of ResolveTeamRefToID.
func (mr *MockTeamResolverMockRecorder) ResolveTeamRefToID(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTeamRefToID", reflect.TypeOf((*MockTeamResolver)(nil).ResolveTeamRefToID), ctx, teamRef)
}
