// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/search.go
//
// Generated by this command:
//
//	mockgen --source=internal/api/search.go --destination=internal/testutil/mock_search_api.go --package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	search "github.com/microsoftgraph/msgraph-sdk-go/search"
	sender "github.com/pzsp-teams/lib/internal/sender"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchAPI is a mock of SearchAPI interface.
type MockSearchAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSearchAPIMockRecorder
	isgomock struct{}
}

// MockSearchAPIMockRecorder is the mock recorder for MockSearchAPI.
type MockSearchAPIMockRecorder struct {
	mock *MockSearchAPI
}

// NewMockSearchAPI creates a new mock instance.
func NewMockSearchAPI(ctrl *gomock.Controller) *MockSearchAPI {
	mock := &MockSearchAPI{ctrl: ctrl}
	mock.recorder = &MockSearchAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchAPI) EXPECT() *MockSearchAPIMockRecorder {
	return m.recorder
}

// SearchChatMessages mocks base method.
func (m *MockSearchAPI) SearchChatMessages(ctx context.Context, queryString string, from, size *int32) (search.QueryPostResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchChatMessages", ctx, queryString, from, size)
	ret0, _ := ret[0].(search.QueryPostResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// SearchChatMessages indicates an expected call of SearchChatMessages.
func (mr *MockSearchAPIMockRecorder) SearchChatMessages(ctx, queryString, from, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchChatMessages", reflect.TypeOf((*MockSearchAPI)(nil).SearchChatMessages), ctx, queryString, from, size)
}
