// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/team.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	sender "github.com/pzsp-teams/lib/internal/sender"
)

// MockTeamAPI is a mock of TeamAPI interface.
type MockTeamAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTeamAPIMockRecorder
}

// MockTeamAPIMockRecorder is the mock recorder for MockTeamAPI.
type MockTeamAPIMockRecorder struct {
	mock *MockTeamAPI
}

// NewMockTeamAPI creates a new mock instance.
func NewMockTeamAPI(ctrl *gomock.Controller) *MockTeamAPI {
	mock := &MockTeamAPI{ctrl: ctrl}
	mock.recorder = &MockTeamAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamAPI) EXPECT() *MockTeamAPIMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockTeamAPI) Archive(ctx context.Context, teamID string, spoReadOnlyForMembers *bool) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, teamID, spoReadOnlyForMembers)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockTeamAPIMockRecorder) Archive(ctx, teamID, spoReadOnlyForMembers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockTeamAPI)(nil).Archive), ctx, teamID, spoReadOnlyForMembers)
}

// CreateFromTemplate mocks base method.
func (m *MockTeamAPI) CreateFromTemplate(ctx context.Context, displayName, description string, owners []string) (string, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, displayName, description, owners)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockTeamAPIMockRecorder) CreateFromTemplate(ctx, displayName, description, owners interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockTeamAPI)(nil).CreateFromTemplate), ctx, displayName, description, owners)
}

// CreateViaGroup mocks base method.
func (m *MockTeamAPI) CreateViaGroup(ctx context.Context, displayName, mailNickname, visibility string) (string, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateViaGroup", ctx, displayName, mailNickname, visibility)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// CreateViaGroup indicates an expected call of CreateViaGroup.
func (mr *MockTeamAPIMockRecorder) CreateViaGroup(ctx, displayName, mailNickname, visibility interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateViaGroup", reflect.TypeOf((*MockTeamAPI)(nil).CreateViaGroup), ctx, displayName, mailNickname, visibility)
}

// Delete mocks base method.
func (m *MockTeamAPI) Delete(ctx context.Context, teamID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamAPIMockRecorder) Delete(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamAPI)(nil).Delete), ctx, teamID)
}

// Get mocks base method.
func (m *MockTeamAPI) Get(ctx context.Context, teamID string) (models.Teamable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamID)
	ret0, _ := ret[0].(models.Teamable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamAPIMockRecorder) Get(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamAPI)(nil).Get), ctx, teamID)
}

// ListMyJoined mocks base method.
func (m *MockTeamAPI) ListMyJoined(ctx context.Context) (models.TeamCollectionResponseable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyJoined", ctx)
	ret0, _ := ret[0].(models.TeamCollectionResponseable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// ListMyJoined indicates an expected call of ListMyJoined.
func (mr *MockTeamAPIMockRecorder) ListMyJoined(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyJoined", reflect.TypeOf((*MockTeamAPI)(nil).ListMyJoined), ctx)
}

// RestoreDeleted mocks base method.
func (m *MockTeamAPI) RestoreDeleted(ctx context.Context, deletedGroupID string) (models.DirectoryObjectable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeleted", ctx, deletedGroupID)
	ret0, _ := ret[0].(models.DirectoryObjectable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// RestoreDeleted indicates an expected call of RestoreDeleted.
func (mr *MockTeamAPIMockRecorder) RestoreDeleted(ctx, deletedGroupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeleted", reflect.TypeOf((*MockTeamAPI)(nil).RestoreDeleted), ctx, deletedGroupID)
}

// Unarchive mocks base method.
func (m *MockTeamAPI) Unarchive(ctx context.Context, teamID string) *sender.RequestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, teamID)
	ret0, _ := ret[0].(*sender.RequestError)
	return ret0
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockTeamAPIMockRecorder) Unarchive(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockTeamAPI)(nil).Unarchive), ctx, teamID)
}

// Update mocks base method.
func (m *MockTeamAPI) Update(ctx context.Context, teamID string, patch *models.Team) (models.Teamable, *sender.RequestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, teamID, patch)
	ret0, _ := ret[0].(models.Teamable)
	ret1, _ := ret[1].(*sender.RequestError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamAPIMockRecorder) Update(ctx, teamID, patch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamAPI)(nil).Update), ctx, teamID, patch)
}
